[book]
authors = ["Ifiok Jr."]
language = "en"
src = "src"
title = "monokit Book"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
site-url = "/monokit/"
git-repository-url = "https://github.com/ifiokjr/monokit"
edit-url-template = "https://github.com/ifiokjr/monokit/edit/main/docs/{path}"
