[package]
name = "monokit_tests"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Integration tests and fixtures for monokit_summary"

[lints]
workspace = true

[dependencies]
insta = { workspace = true }
monokit_summary = { path = "../monokit_summary", features = ["all-grammars"] }

[[test]]
name = "outline"
path = "src/outline.rs"

[[test]]
name = "summary"
path = "src/summary.rs"
